name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SQLite
        run: brew install sqlite

      - name: Build server
        run: make

      - name: Build client
        run: make client
